version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get install -y unzip && apt-get install -y jq
      - echo "Buscando credenciais do Secrets Manager..."
      - SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id CICD_User --region us-east-1 --query 'SecretString' --output text)
      - export AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r .AWS_ACCESS_KEY_ID)
      - export AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r .AWS_SECRET_ACCESS_KEY)
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set default.region us-east-1
      - aws s3 ls
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Iniciando o pré-build..."
      - terraform init

  build:
    commands:
      - echo "Validando configuração do Terraform..."
      - terraform validate
      - echo "Planejando mudanças..."
      - terraform plan

  post_build:
    commands:
      - echo "Aplicando mudanças..."
      - terraform apply -auto-approve
      - echo "Deploy concluído!"
